"""Print a topic inventory of the corpus and save it to eval/corpus_overview.md.

For each document: title, word count, last-updated date and its main headings. Used to plan
evaluation questions by hand.

Usage:
    python scripts/data/summarise_corpus.py
"""

from __future__ import annotations

import json
import re
import sys

from rag.config import PROJECT_ROOT, RAW_DIR

OUT_FILE = PROJECT_ROOT / "eval" / "corpus_overview.md"
MAX_HEADINGS = 15  # per document, to keep the overview readable


def main_headings(text: str) -> list[str]:
    """Return the top two heading levels present in a document, in order."""
    headings = [
        (len(m.group(1)), m.group(2).strip())
        for m in re.finditer(r"^(#{1,6})\s+(.+)$", text, flags=re.MULTILINE)
    ]
    if not headings:
        return []
    top = min(level for level, _ in headings)
    return [h if level == top else f"  {h}" for level, h in headings if level <= top + 1]


def build_overview(docs: list[dict]) -> str:
    total_words = sum(len(d["text"].split()) for d in docs)
    lines = [
        "# Corpus overview",
        "",
        f"{len(docs)} GOV.UK documents, {total_words:,} words in total. "
        "Generated by `scripts/data/summarise_corpus.py`; do not edit by hand.",
        "",
        "Contains public sector information licensed under the Open Government Licence v3.0.",
        "",
        "| # | Document | Words | Last updated on GOV.UK |",
        "|---|---|---:|---|",
    ]
    for n, doc in enumerate(docs, start=1):
        updated = (doc.get("last_updated") or "unknown")[:10]
        words = len(doc["text"].split())
        lines.append(f"| {n} | [{doc['title']}]({doc['url']}) | {words:,} | {updated} |")

    for n, doc in enumerate(docs, start=1):
        lines += ["", f"## {n}. {doc['title']}", "", f"<{doc['url']}>", ""]
        headings = main_headings(doc["text"])
        for heading in headings[:MAX_HEADINGS]:
            indent = "  " if heading.startswith("  ") else ""
            lines.append(f"{indent}- {heading.strip()}")
        if len(headings) > MAX_HEADINGS:
            lines.append(f"- … and {len(headings) - MAX_HEADINGS} more headings")
        if not headings:
            lines.append("- (no headings)")
    return "\n".join(lines) + "\n"


def main() -> int:
    docs = [json.loads(p.read_text(encoding="utf-8")) for p in sorted(RAW_DIR.glob("*.json"))]
    if not docs:
        print(f"No documents in {RAW_DIR}. Run scripts/data/download_docs.py first.")
        return 1
    docs.sort(key=lambda d: d["title"].lower())

    overview = build_overview(docs)
    OUT_FILE.write_text(overview, encoding="utf-8")
    sys.stdout.reconfigure(encoding="utf-8")
    print(overview)
    print(f"Saved to {OUT_FILE.relative_to(PROJECT_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
