"""Report how the test set covers question types, splits and source documents.

Writes eval/coverage.md: progress against the target mix, and the documents that no
question uses yet, to spot gaps. Example items are excluded from every count.

Usage:
    python scripts/testset/question_coverage.py
"""

from __future__ import annotations

import argparse
import sys
from collections import Counter
from pathlib import Path

from rag.config import PROJECT_ROOT, RAW_DIR
from rag.evaluation.schema import QUESTION_TYPES, EvalItem, load_items
from rag.evaluation.utils import load_corpus

QUESTIONS_FILE = PROJECT_ROOT / "eval" / "questions.jsonl"
OUT_FILE = PROJECT_ROOT / "eval" / "coverage.md"
TARGETS = {"factual": 60, "multi_passage": 20, "informal": 10, "unanswerable": 10}
HELDOUT_TARGET = 20


def bar(done: int, target: int, width: int = 20) -> str:
    filled = min(width, round(width * done / target)) if target else width
    return "█" * filled + "░" * (width - filled)


def build_coverage(items: list[EvalItem], docs: dict[str, dict]) -> str:
    examples = [i for i in items if i.is_example]
    real = [i for i in items if not i.is_example]
    by_type = Counter(i.question_type for i in real)
    total_target = sum(TARGETS.values())

    lines = [
        "# Test set coverage",
        "",
        "Generated by `scripts/testset/question_coverage.py`; do not edit by hand. "
        f"Counts exclude {len(examples)} example item(s).",
        "",
        f"**{len(real)} of {total_target} questions written.**",
        "",
        "## By question type",
        "",
        "| Type | Written | Target | Progress |",
        "|---|---:|---:|---|",
    ]
    for question_type in QUESTION_TYPES:
        done, target = by_type[question_type], TARGETS[question_type]
        lines.append(f"| {question_type} | {done} | {target} | `{bar(done, target)}` |")
    lines.append(
        f"| **total** | **{len(real)}** | **{total_target}** | `{bar(len(real), total_target)}` |"
    )

    by_split = Counter(i.split for i in real)
    by_author = Counter(i.author for i in real)
    evidence_sizes = Counter(len(i.evidence) for i in real if i.answerable)
    lines += [
        "",
        "## By split and author",
        "",
        f"- Split: dev {by_split['dev']}, held-out {by_split['heldout']} "
        f"(target {HELDOUT_TARGET}, assigned once by `scripts/testset/split_questions.py`)",
        "- Author: " + (", ".join(f"{a} {n}" for a, n in sorted(by_author.items())) or "none"),
        "- Evidence quotes per answerable question: "
        + (", ".join(f"{k}: {v}" for k, v in sorted(evidence_sizes.items())) or "none"),
    ]

    cited: Counter = Counter()
    for item in real:
        for doc_id in {e.doc_id for e in item.evidence}:
            cited[doc_id] += 1
    lines += [
        "",
        "## By source document",
        "",
        "Number of questions with evidence from each document.",
        "",
        "| Questions | Document | Words |",
        "|---:|---|---:|",
    ]
    for doc_id in sorted(docs, key=lambda d: (-cited[d], docs[d]["title"].lower())):
        if cited[doc_id]:
            words = len(docs[doc_id]["text"].split())
            lines.append(f"| {cited[doc_id]} | {docs[doc_id]['title']} | {words:,} |")

    uncovered = [d for d in docs if not cited[d]]
    lines += [
        "",
        f"## Documents with no questions ({len(uncovered)} of {len(docs)})",
        "",
        "Largest first, as these are the biggest gaps.",
        "",
    ]
    for doc_id in sorted(uncovered, key=lambda d: -len(docs[d]["text"].split())):
        words = len(docs[doc_id]["text"].split())
        lines.append(f"- {docs[doc_id]['title']} ({words:,} words) `{doc_id}`")
    unknown = sorted(set(cited) - set(docs))
    if unknown:
        lines += ["", "**Evidence cites unknown documents:** " + ", ".join(unknown)]
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--questions", type=Path, default=QUESTIONS_FILE)
    parser.add_argument("--corpus", type=Path, default=RAW_DIR)
    parser.add_argument("--out", type=Path, default=OUT_FILE)
    args = parser.parse_args()
    sys.stdout.reconfigure(encoding="utf-8")

    report = build_coverage(load_items(args.questions), load_corpus(args.corpus))
    args.out.write_text(report, encoding="utf-8")
    print(report)
    print(f"Saved to {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
